[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "streamlit run quartr_streamlit.py --server.address 0.0.0.0 --server.port $PORT"
restartPolicyType = "ON_FAILURE"
