[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -m streamlit run quartr_streamlit.py --server.address 0.0.0.0 --server.port $PORT"
restartPolicyType = "ON_FAILURE"

[env]
PYTHON_VERSION = "3.9"
